version: '3.8'
services:
  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DB_API_URL=${DB_API_URL}
      - REDIS_URL=${REDIS_URL}
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data: