services:
  - type: web
    name: facelook_backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DB_API_URL
        sync: false
      - key: REDIS_URL
        sync: false
    healthCheckPath: /health
    numInstances: 1
    ports:
      - port: 3001
        protocol: TCP